/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Flex, Icon, Text, View } from "@aws-amplify/ui-react";
export default function Calendar(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="356px"
      height="345px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      overflow="hidden"
      position="relative"
      borderRadius="16px"
      padding="0px 0px 0px 0px"
      backgroundColor="rgba(255,255,255,1)"
      {...getOverrideProps(overrides, "Calendar")}
      {...rest}
    >
      <Icon
        width="36px"
        height="36px"
        viewBox={{ minX: 0, minY: 0, width: 36, height: 36 }}
        paths={[
          {
            d: "M36 18C36 27.9411 27.9411 36 18 36C8.05887 36 0 27.9411 0 18C0 8.05887 8.05887 0 18 0C27.9411 0 36 8.05887 36 18Z",
            fill: "rgba(229,240,255,1)",
            fillRule: "nonzero",
          },
        ]}
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="103px"
        left="160px"
        {...getOverrideProps(overrides, "Ellipse 50")}
      ></Icon>
      <View
        width="189px"
        height="36px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="179px"
        left="82px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(229,240,255,1)"
        {...getOverrideProps(overrides, "Rectangle 514")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="24px"
        fontWeight="700"
        color="rgba(22,22,29,1)"
        lineHeight="28.80000114440918px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="22px"
        left="28px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Calendar"
        {...getOverrideProps(overrides, "Title")}
      ></Text>
      <Flex
        gap="10px"
        direction="row"
        width="unset"
        height="unset"
        justifyContent="flex-start"
        alignItems="flex-start"
        position="absolute"
        top="27px"
        left="229px"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Frame 125")}
      >
        <Text
          fontFamily="Inter"
          fontSize="14px"
          fontWeight="400"
          color="rgba(139,139,167,1)"
          lineHeight="19.600000381469727px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          shrink="0"
          position="relative"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="April 2023"
          {...getOverrideProps(overrides, "April 2023")}
        ></Text>
        <View
          width="20px"
          height="20px"
          {...getOverrideProps(overrides, "CaretDown")}
        ></View>
      </Flex>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="500"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 89.5px)"
        left="calc(50% - 12px - 138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Mo"
        {...getOverrideProps(overrides, "Mo")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="500"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 89.5px)"
        left="calc(50% - 12px - 92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Tu"
        {...getOverrideProps(overrides, "Tu")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="500"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 89.5px)"
        left="calc(50% - 12px - 46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="We"
        {...getOverrideProps(overrides, "We")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="500"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 89.5px)"
        left="calc(50% - 12px - 0px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Th"
        {...getOverrideProps(overrides, "Th")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="500"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 89.5px)"
        left="calc(50% - 12px - -46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Fri"
        {...getOverrideProps(overrides, "Fri")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="500"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 89.5px)"
        left="calc(50% - 12px - -92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Sa"
        {...getOverrideProps(overrides, "Sa")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="500"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 89.5px)"
        left="calc(50% - 12px - -138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Su"
        {...getOverrideProps(overrides, "Su")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 51.5px)"
        left="calc(50% - 9px - 138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="29"
        {...getOverrideProps(overrides, "29607601")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 51.5px)"
        left="calc(50% - 12px - 92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="30"
        {...getOverrideProps(overrides, "30607603")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 51.5px)"
        left="calc(50% - 12px - 46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="31"
        {...getOverrideProps(overrides, "31")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 51.5px)"
        left="calc(50% - 12px - 0px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="1"
        {...getOverrideProps(overrides, "1607608")}
      ></Text>
      <Icon
        width="36px"
        height="36px"
        viewBox={{ minX: 0, minY: 0, width: 36, height: 36 }}
        paths={[
          {
            d: "M36 18C36 27.9411 27.9411 36 18 36C8.05887 36 0 27.9411 0 18C0 8.05887 8.05887 0 18 0C27.9411 0 36 8.05887 36 18Z",
            fill: "rgba(0,106,255,1)",
            fillRule: "nonzero",
          },
        ]}
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="179px"
        left="68px"
        {...getOverrideProps(overrides, "Ellipse 48")}
      ></Icon>
      <Icon
        width="36px"
        height="36px"
        viewBox={{ minX: 0, minY: 0, width: 36, height: 36 }}
        paths={[
          {
            d: "M36 18C36 27.9411 27.9411 36 18 36C8.05887 36 0 27.9411 0 18C0 8.05887 8.05887 0 18 0C27.9411 0 36 8.05887 36 18Z",
            fill: "rgba(0,106,255,1)",
            fillRule: "nonzero",
          },
        ]}
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="179px"
        left="252px"
        {...getOverrideProps(overrides, "Ellipse 49")}
      ></Icon>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 51.5px)"
        left="calc(50% - 12px - -46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2"
        {...getOverrideProps(overrides, "2607610")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 51.5px)"
        left="calc(50% - 12px - -92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="3"
        {...getOverrideProps(overrides, "3607612")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 51.5px)"
        left="calc(50% - 12px - -138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="4"
        {...getOverrideProps(overrides, "4607614")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 13.5px)"
        left="calc(50% - 12px - 138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="5"
        {...getOverrideProps(overrides, "5607616")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 13.5px)"
        left="calc(50% - 12px - 92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="6"
        {...getOverrideProps(overrides, "6607618")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 13.5px)"
        left="calc(50% - 12px - 46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="7"
        {...getOverrideProps(overrides, "7607620")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 13.5px)"
        left="calc(50% - 12px - 0px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="8"
        {...getOverrideProps(overrides, "8607622")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 13.5px)"
        left="calc(50% - 12px - -46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="9"
        {...getOverrideProps(overrides, "9607624")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 13.5px)"
        left="calc(50% - 12px - -92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="10"
        {...getOverrideProps(overrides, "10")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - 13.5px)"
        left="calc(50% - 12px - -138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="11"
        {...getOverrideProps(overrides, "11")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -24.5px)"
        left="calc(50% - 12px - 138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="12"
        {...getOverrideProps(overrides, "12")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="500"
        color="rgba(255,255,255,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -24.5px)"
        left="calc(50% - 12px - 92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="13"
        {...getOverrideProps(overrides, "13")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,106,255,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -24.5px)"
        left="calc(50% - 12px - 46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="14"
        {...getOverrideProps(overrides, "14")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,106,255,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -24.5px)"
        left="calc(50% - 12px - 0px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="15"
        {...getOverrideProps(overrides, "15")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,106,255,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -24.5px)"
        left="calc(50% - 12px - -46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="16"
        {...getOverrideProps(overrides, "16")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="500"
        color="rgba(255,255,255,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -24.5px)"
        left="calc(50% - 12px - -92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="17"
        {...getOverrideProps(overrides, "17")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -24.5px)"
        left="calc(50% - 12px - -138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="18"
        {...getOverrideProps(overrides, "18")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -62.5px)"
        left="calc(50% - 12px - 138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="19"
        {...getOverrideProps(overrides, "19")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -62.5px)"
        left="calc(50% - 12px - 92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="20"
        {...getOverrideProps(overrides, "20")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -62.5px)"
        left="calc(50% - 12px - 46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="21"
        {...getOverrideProps(overrides, "21")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -62.5px)"
        left="calc(50% - 12px - 0px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="22"
        {...getOverrideProps(overrides, "22")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -62.5px)"
        left="calc(50% - 12px - -46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="23"
        {...getOverrideProps(overrides, "23")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -62.5px)"
        left="calc(50% - 12px - -92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="24"
        {...getOverrideProps(overrides, "24")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -62.5px)"
        left="calc(50% - 12px - -138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="25"
        {...getOverrideProps(overrides, "25")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -100.5px)"
        left="calc(50% - 12px - 138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="26"
        {...getOverrideProps(overrides, "26")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -100.5px)"
        left="calc(50% - 12px - 92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="27"
        {...getOverrideProps(overrides, "27")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -100.5px)"
        left="calc(50% - 12px - 46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="28"
        {...getOverrideProps(overrides, "28")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -100.5px)"
        left="calc(50% - 12px - 0px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="29"
        {...getOverrideProps(overrides, "29607665")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(22,22,29,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -100.5px)"
        left="calc(50% - 12px - -46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="30"
        {...getOverrideProps(overrides, "30607668")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -100.5px)"
        left="calc(50% - 12px - -92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="1"
        {...getOverrideProps(overrides, "1607670")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -100.5px)"
        left="calc(50% - 12px - -138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2"
        {...getOverrideProps(overrides, "2607672")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -138.5px)"
        left="calc(50% - 12px - 138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="3"
        {...getOverrideProps(overrides, "3607674")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -138.5px)"
        left="calc(50% - 12px - 92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="4"
        {...getOverrideProps(overrides, "4607676")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -138.5px)"
        left="calc(50% - 12px - 46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="5"
        {...getOverrideProps(overrides, "5607678")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -138.5px)"
        left="calc(50% - 12px - 0px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="6"
        {...getOverrideProps(overrides, "6607680")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -138.5px)"
        left="calc(50% - 12px - -46px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="7"
        {...getOverrideProps(overrides, "7607682")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -138.5px)"
        left="calc(50% - 12px - -92px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="8"
        {...getOverrideProps(overrides, "8607684")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="14px"
        fontWeight="400"
        color="rgba(168,168,189,1)"
        lineHeight="19.600000381469727px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="24px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="calc(50% - 10px - -138.5px)"
        left="calc(50% - 12px - -138px)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="9"
        {...getOverrideProps(overrides, "9607686")}
      ></Text>
    </View>
  );
}
