/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://6x27zb6zyfhahlqioya5eilj5a.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qnp26ykiovagnkpxdd62wpvtta",
    "aws_cognito_identity_pool_id": "eu-north-1:5770bedd-ec49-41c1-90dc-9300fa0d9729",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_OaF5Ii85l",
    "aws_user_pools_web_client_id": "ammoqqe40pnrokkf0ebljpeqg",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "API": {
        "GraphQL": {
            "endpoint": "https://6x27zb6zyfhahlqioya5eilj5a.appsync-api.eu-north-1.amazonaws.com/graphql",
            "region": "eu-north-1",
            "defaultAuthMode": "apiKey",
            "apiKey": "da2-qnp26ykiovagnkpxdd62wpvtta"
        },
        "DataStore": {
            "authMode": "API_KEY"
        }
    }
};


export default awsmobile;
